"""WinSim — Mission definitions (data-driven)."""

MISSIONS = [
    {
        "id": "launch_app",
        "title": "Launch an Application",
        "desc": "Open Notepad from the desktop.",
        "target_app": "Notepad",
        "type": "launch",
        "xp": 10,
        "time_limit": 30,
    },
    {
        "id": "kill_runaway",
        "title": "Runaway Process!",
        "desc": "A process is eating 80%+ CPU. Find it and kill it.",
        "type": "kill_high_cpu",
        "threshold": 40.0,
        "xp": 25,
        "time_limit": 45,
        "spawn": {"name": "chrome.exe", "cpu_base": 55.0, "ram_base": 400,
                   "icon": "CR", "colour": "#4caf50", "description": "Chrome (runaway)"},
    },
    {
        "id": "free_memory",
        "title": "Memory Pressure!",
        "desc": "RAM is above 85%. Free at least 200 MB by killing non-essential processes.",
        "type": "free_ram",
        "target_mb": 200,
        "xp": 30,
        "time_limit": 60,
    },
    {
        "id": "find_malware",
        "title": "Suspicious Activity",
        "desc": "An unknown process is running. Find and terminate it.",
        "type": "kill_malware",
        "xp": 40,
        "time_limit": 45,
    },
    {
        "id": "optimize_startup",
        "title": "Slow Boot",
        "desc": "Too many startup services. Disable at least 2 non-essential services.",
        "type": "disable_services",
        "target_count": 2,
        "xp": 35,
        "time_limit": 60,
    },
    {
        "id": "clean_disk",
        "title": "Disk Almost Full",
        "desc": "Disk usage is high. Delete temp files to free at least 300 MB.",
        "type": "free_disk",
        "target_mb": 300,
        "xp": 20,
        "time_limit": 45,
    },
    {
        "id": "priority_fix",
        "title": "Laggy Video Call",
        "desc": "Set a process to High priority to fix lag.",
        "type": "set_priority",
        "target_priority": 13,
        "xp": 30,
        "time_limit": 30,
        "spawn": {"name": "zoom.exe", "cpu_base": 6.0, "ram_base": 180,
                   "icon": "ZM", "colour": "#2d8cff", "description": "Zoom (laggy)"},
    },
]
